export const bands = [
  {
    id: 1,
    name: "Living With Ghosts",
    genre: "Pop-Punk",
    yearFormed: 2022,
    numOfMembers: 4,
  },
  {
    id: 2,
    name: "Boston Manor",
    genre: "Rock",
    yearFormed: 2013,
    numOfMembers: 5,
  },
  {
    id: 3,
    name: "The 1975",
    genre: "Alternative",
    yearFormed: 2010,
    numOfMembers: 4,
  },
  {
    id: 4,
    name: "Spiritbox",
    genre: "Metal",
    yearFormed: 2016,
    numOfMembers: 3,
  },
  {
    id: 5,
    name: "Dance Gavin Dance",
    genre: "Post-Hardcore",
    yearFormed: 2006,
    numOfMembers: 5,
  },
  {
    id: 6,
    name: "Don Broco",
    genre: "Rock",
    yearFormed: 2014,
    numOfMembers: 4,
  },
  {
    id: 7,
    name: "Neck Deep",
    genre: "Pop-Punk",
    yearFormed: 2015,
    numOfMembers: 6,
  },
  {
    id: 8,
    name: "Waterparks",
    genre: "Pop-Punk",
    yearFormed: 2012,
    numOfMembers: 3,
  },
  {
    id: 9,
    name: "Purity Ring",
    genre: "Electronic",
    yearFormed: 2010,
    numOfMembers: 2,
  },
  {
    id: 10,
    name: "Interpol",
    genre: "Alternative",
    yearFormed: 2004,
    numOfMembers: 3,
  },
];
